routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Clients\ClientController@index')->name('client.home');

Route::get('barang/', 'Clients\ClientController@showBarang')->name('client.show_barang');

Route::get('barang/{slug}', 'Clients\ClientController@detailBarang')->name('client.detail_barang');

Route::get('barang/kategori/{id}', 'Clients\ClientController@showKategori')->name('client.kategori');

Route::get('barang/search','Clients\ClientController@searchBarang')->name('barang.search');

Route::get('about', function(){
    return view('client.about');
});

Route::namespace('Clients')->group(function() {
    Route::get('register/', 'PelangganLoginController@showRegisterForm')->name('pelanggan.registerForm');
    Route::post('register', 'PelangganLoginController@register')->name('pelanggan.register');
    Route::get('login', 'PelangganLoginController@showLoginForm')->name('pelanggan.loginForm');
    Route::post('login', 'PelangganLoginController@login')->name('pelanggan.login');
    Route::post('logout', 'PelangganLoginController@logout')->name('pelanggan.logout');
    //auth

    Route::middleware('auth.client:pelanggan')->group(function(){
        Route::get('profile/{id}', 'PelangganController@index')->name('pelanggan.profile');
        Route::get('profile/edit/{id}', 'PelangganController@edit')->name('pelanggan.edit-profile');
        Route::put('profile/edit/{id}', 'PelangganController@update')->name('pelanggan.update');
        Route::get('profile/ganti_password/{id}', 'PelangganController@changePassword')->name('pelanggan.change_password');
        Route::put('profile/ganti_password/{id}', 'PelangganController@updatePassword')->name('pelanggan.update_password');
        
        Route::put('riwayat_pesanan/detail/{id}/terima', 'PelangganController@terimaBarang')->name('pelanggan.terima_barang');

        Route::get('barang-disukai', 'LikeController@index')->name('pelanggan.liked-items');

        Route::get('checkout', function() {
            return view('client.checkout.form', ['user' => Auth::guard('pelanggan')->user()]);
        })->name('client.checkout');
        
        Route::get('riwayat_pesanan', 'PelangganController@riwayatPesanan')->name('pelanggan.riwayat_pesanan');
        Route::get('riwayat_pesanan/detail/{id}', 'PelangganController@detailPesanan')->name('pelanggan.detail_pesanan');
        Route::get('riwayat_pesanan/detail', function(){
            return redirect()->back();
        });

        Route::put('riwayat_pesanan/cancel/{id}', 'ClientController@cancelOrder')->name('pelanggan.cancel_order');

        //komentar
        Route::post('barang/{slug}/comment', 'KomenController@create')->name('pelanggan.komen');
        
        Route::post('place-order', 'ClientController@placeOrder')->name('pelanggan.order');

        Route::get('thankyou/{id}', 'ClientController@thankyou')->name('pelanggan.order.thankyou');
    });
});

Route::prefix('doku')->group(function() {
    Route::post('identify', 'DokuController@identify');
    Route::post('notify', 'DokuController@notify');
    Route::post('redirect', 'DokuController@redirect');
});

Route::group(['prefix'  => 'api/cart', 'namespace' => 'Api'], function() {
    Route::get('all', 'CartController@cartList')->name('api.cart.all');
    Route::post('add', 'CartController@addToCart')->name('api.cart.add');
    Route::post('update', 'CartController@updateCart')->name('api.cart.update');
    Route::post('delete/{barang}', 'CartController@deleteCart')->name('api.cart.delete');

});

Route::group(['prefix' => 'api/', 'namespace' => 'Api'], function() {
    Route::middleware('auth.client:pelanggan')->group(function() {
        Route::get('likes', 'LikeController@index')->name('api.like.index');
        Route::post('likes/{item_id}', 'LikeController@create')->name('api.like.add');
        Route::post('likes/{item_id}/remove', 'LikeController@remove')->name('api.like.remove');
    });
    Route::get('cost', 'ShippingController@shippingCost')->name('api.shipping.cost');
});

Route::get('/test', function(){
	return view('default');
});


Route::get('admin/', function(){
    return redirect()->route('admin.home');
});

Route::prefix('admin')->group(function() {

    Route::middleware('auth')->group(function() {
        Route::resource('kategori', 'KategoriController');
        Route::get('dashboard', 'HomeController@index')->name('admin.home');
        Route::resource('barang', 'BarangController');
        Route::resource('user', 'UserController');
        Route::get('trash-barang', 'BarangController@showTrash')->name('barang.trash');
        Route::get('barang/{id}/restore', 'BarangController@restore')->name('barang.restore');
        Route::get('pelanggan', 'PelangganController@index')->name('pelanggan.index');
        Route::delete('pelanggan/{id}', 'PelangganController@destroy')->name('pelanggan.destroy');
        Route::resource('pemesanan', 'PemesananController');
        Route::resource('pembayaran', 'PaymentController');


        Route::get('laporan-penjualan', 'LaporanController@laporanPenjualan')->name('laporan.penjualan');

        Route::get('laporan-penjualan/print', 'LaporanController@cetakPenjualan')->name('print.penjualan');

        Route::get('laporan-stock', 'LaporanController@laporanStock')->name('laporan.stock');

        Route::get('laporan-stock/print', 'LaporanController@cetakStock')->name('print.stock');
    });
    
    Auth::routes();
});

resources/views/admin/app.blade.php
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../../assets/images/favicon.png">
    <title>@yield('title') - Surya Artshop</title>
    <!-- TOAST FLASH MESSAGE-->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"> 
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ asset('select2/dist/css/select2.min.css') }}">
    <link href="{{ asset('css/style.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/custom.css') }}">
    <link href="{{ asset('css/icons/fontawesome/css/all.min.css') }}" rel="stylesheet"> 
    <!-- Data Tables -->
    <link rel="stylesheet" href="{{ asset('DataTables/DataTables-1.10.16/css/dataTables.bootstrap4.min.css') }}">
    @stack('styles')
</head>

<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    @guest 
        @yield('content')
    @else

    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">

        @include('admin.navbar')

        @include('admin.sidebar')

        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <div class="page-breadcrumb">
                <div class="row">
                    <div class="col-12 d-flex no-block align-items-center">
                        <h4 class="page-title">@yield('title')</h4>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Bread crumb and right sidebar toggle -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- FORM ERROR VALIDATION -->
                @if($errors->any())
                    <div class="row">
                        <div class="col-md-6">
                            <div class="alert alert-danger">
                                <ul>
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                                </ul>
                                
                            </div>
                        </div>
                    </div>
                @endif
                @yield('content')   
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->

            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <br>
            <footer class="footer text-center">
                Copyright by Surya Bali ART</a>.
            </footer>
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    @endguest
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{{ asset('jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{ asset('popper.js/dist/umd/popper.min.js') }}"></script>
    <script src="{{ asset('bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js') }}"></script>
    <script src="{{ asset('sparkline/sparkline.js') }}"></script>
    <!--Wave Effects -->
    <script src="{{ asset('js/waves.js') }}"></script>
    <!--Menu sidebar -->
    <script src="{{ asset('js/sidebarmenu.js') }}"></script>
    <!-- TOAST FLASH MESSAGE -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <!--Custom JavaScript -->
    <script src="{{ asset('js/custom.min.js')}}"></script>

    @include('admin.toast')
    @stack('scripts')

</body>

</html>

resources/views/admin/dashboard.blade.php
@extends('admin.app')

@section('title')
    Dashboard
@endsection

@section('content')
    <div class="row">
        <div class="col-md-4">
            <div class="card card-hover">
                <div class="box bg-primary text-center">
                    <h1 class="font-light text-white"><i class="mdi mdi-cart"></i> <?= $total_pesanan ?></h1>
                    <h6 class="text-white">Total Pesanan Masuk</h6>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-hover">
                <div class="box bg-success text-center">
                    <h1 class="font-light text-white"><i class="fa fa-users"></i> <?= $total_pelanggan ?></h1>
                    <h6 class="text-white">Total Pelanggan</h6>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-hover">
                <div class="box bg-secondary text-center">
                    <h1 class="font-light text-white"><i class="fa fa-box"></i> <?= $total_produk ?></h1>
                    <h6 class="text-white">Total Produk</h6>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <p>Selamat Datang {{ (Auth::user()->level) ? 'Owner' : 'Admin' }} :)</p>
                    
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/navbar.blade.php
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar" data-navbarbg="skin5">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header" data-logobg="skin5">
                    <!-- This is for the sidebar toggle which is visible on mobile only -->
                    <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i class="ti-menu ti-close"></i></a>
                    <!-- ============================================================== -->
                    <!-- Logo -->
                    <!-- ============================================================== -->
                    <a class="navbar-brand" href="{{ route('admin.home') }}">
                        <!-- Logo icon -->
                        <b class="logo-icon p-l-10">
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            <img src="{{ asset('images/logo-icon.png') }}" alt="homepage" class="light-logo" />
                           
                        </b>
                        <!--End Logo icon -->
                         <!-- Logo text -->
                        <span class="logo-text">
                             SURYA BALI ART
                        </span>
                    
                    </a>
                    <!-- ============================================================== -->
                    <!-- End Logo -->
                    <!-- ============================================================== -->
                    <!-- ============================================================== -->
                    <!-- Toggle which is visible on mobile only -->
                    <!-- ============================================================== -->
                    <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i class="ti-more"></i></a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse collapse" id="navbarSupportedContent" data-navbarbg="skin5">
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav float-left mr-auto">
                        <li class="nav-item d-none d-md-block"><a class="nav-link sidebartoggler waves-effect waves-light" href="javascript:void(0)" data-sidebartype="mini-sidebar"><i class="mdi mdi-menu font-24"></i></a></li>
                       
                        <!-- ============================================================== -->
                        <!-- Search -->
                        <!-- ============================================================== -->
                        <li class="nav-item search-box"> <a class="nav-link waves-effect waves-dark" href="javascript:void(0)"><i class="ti-search"></i></a>
                            <form class="app-search position-absolute" method="get">
                                <input type="text" class="form-control" name="q" value="{{ request()->has('q') ? request()->get('q') : '' }}" placeholder="Search &amp; enter"> <a class="srh-btn"><i class="ti-close"></i></a>
                            </form>
                        </li>
                    </ul>
                    <!-- ============================================================== -->
                    <!-- Right side toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav float-right">
                        
                        

                        <!-- ============================================================== -->
                        <!-- User profile and search -->
                        <!-- ============================================================== -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="{{ asset('/images/1.jpg')}}" alt="user" class="rounded-circle" width="31"></a>
                            <div class="dropdown-menu dropdown-menu-right user-dd animated">
                                 <div class="dropdown-divider"></div>                                                           
                                <form action="{{ route('logout') }}" method="post">
                                    @csrf
                                    <button type="submit" class="dropdown-item"><i class="fa fa-power-off m-r-5 m-l-5"></i> Logout</button>
                                </form>
                                
                            </div>
                        </li>
                        <!-- ============================================================== -->
                        <!-- User profile and search -->
                        <!-- ============================================================== -->
                    </ul>
                </div>
            </nav>
        </header>
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->

resources/views/admin/sidebar.blade.php
        @guest
            <div>
        @else
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <aside class="left-sidebar" data-sidebarbg="skin5">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="p-t-30">
                        <li class="sidebar-item {{ urlHasPrefix('dashboard') ? 'selected' : '' }} "> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ route('admin.home') }}"><i class="mdi mdi-view-dashboard"></i><span class="hide-menu">Dashboard</span></a></li>
                        <li class="sidebar-item {{ urlHasPrefix('kategori') ? 'selected' : '' }}"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ route('kategori.index') }}"><i class="mdi mdi-equal-box"></i><span class="hide-menu">Kategori Barang</span></a></li>
                        <li class="sidebar-item {{ urlHasPrefix('barang') ? 'active' : '' }}"> 
                        
                            <!-- <a class="sidebar-link has-arrow waves-effect waves-dark sidebar-link" href="#">
                            <i class="fas fa-box"></i><span class="hide-menu">Manage Barang</span></a> -->
                            <!-- <ul class="collapse first-level {{ urlHasPrefix('stok') ? 'selected' : '' }}">
                                <li class="sidebar-item"> -->
                                        <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ route('barang.index') }}">
                                        <i class="fas fa-box"></i><span class="hide-menu">Barang</span></a>
                                <!-- </li> -->
                                <!-- <li class="sidebar-item {{ urlHasPrefix('trash') ? 'selected' : '' }}"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ route('barang.trash') }}"><i class="fas fa-trash"></i><span class="hide-menu">Trash Barang</span></a></li> -->
                            <!-- </ul> -->
                        </li>
                        @if(Auth::user()->level == 1) 
                        <li class="sidebar-item {{ urlHasPrefix('user') ? 'selected' : '' }}"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ route('user.index') }}"><i class="fas fa-user"></i><span class="hide-menu">User</span></a></li>
                        @endif
                        <li class="sidebar-item {{ urlHasPrefix('pelanggan') ? 'selected' : '' }}"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ route('pelanggan.index') }}"><i class="mdi mdi-account-multiple"></i><span class="hide-menu">Pelanggan</span></a></li>
                        <li class="sidebar-item {{ urlHasPrefix('pemesanan') ? 'selected' : '' }}"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ route('pemesanan.index') }}"><i class="mdi mdi-cart"></i><span class="hide-menu">Pemesanan</span></a></li>
                        <li class="sidebar-item {{ urlHasPrefix('pembayaran') ? 'selected' : '' }}"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ route('pembayaran.index') }}"><i class="fas fa-money-bill-wave"></i><span class="hide-menu">Pembayaran</span></a></li>
                        
                        @if(Auth::user()->level == 1) 
                            <li class="sidebar-item {{ urlHasPrefix('laporan-penjualan') ? 'selected' : '' }}"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ url('admin/laporan-penjualan') }}"><i class="fa fa-list"></i><span class="hide-menu">Laporan Penjualan</span></a></li>
                            <li class="sidebar-item {{ urlHasPrefix('laporan-stock') ? 'selected' : '' }}"> <a class="sidebar-link waves-effect waves-dark sidebar-link" href="{{ url('admin/laporan-stock') }}"><i class="fa fa-list"></i><span class="hide-menu">Laporan Stock</span></a></li>                    
                        @endif
                    
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        @endguest

resources/views/admin/toast.blade.php
@if(Session::get('success'))
<script>
    toastr.success('<?= Session::get('success') ?>', 'Success', {timeOut:0});
</script>
<?php Session::forget('success') ?>
@endif

@if(Session::get('warning'))
<script>
    toastr.warning('<?= Session::get('warning') ?>', 'Warning', {timeOut:5000});
</script>
<?php Session::forget('warning') ?>
@endif

@if(Session::get('danger'))
<script>
    toastr.error('<?= Session::get('danger') ?>', 'Error', {timeOut:5000});
</script>
<?php Session::forget('danger') ?>
@endif