routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Clients\ClientController@index')->name('client.home');

Route::get('barang/', 'Clients\ClientController@showBarang')->name('client.show_barang');

Route::get('barang/{slug}', 'Clients\ClientController@detailBarang')->name('client.detail_barang');

Route::get('barang/kategori/{id}', 'Clients\ClientController@showKategori')->name('client.kategori');

Route::get('barang/search','Clients\ClientController@searchBarang')->name('barang.search');

Route::get('about', function(){
    return view('client.about');
});

Route::namespace('Clients')->group(function() {
    Route::get('register/', 'PelangganLoginController@showRegisterForm')->name('pelanggan.registerForm');
    Route::post('register', 'PelangganLoginController@register')->name('pelanggan.register');
    Route::get('login', 'PelangganLoginController@showLoginForm')->name('pelanggan.loginForm');
    Route::post('login', 'PelangganLoginController@login')->name('pelanggan.login');
    Route::post('logout', 'PelangganLoginController@logout')->name('pelanggan.logout');
    //auth

    Route::middleware('auth.client:pelanggan')->group(function(){
        Route::get('profile/{id}', 'PelangganController@index')->name('pelanggan.profile');
        Route::get('profile/edit/{id}', 'PelangganController@edit')->name('pelanggan.edit-profile');
        Route::put('profile/edit/{id}', 'PelangganController@update')->name('pelanggan.update');
        Route::get('profile/ganti_password/{id}', 'PelangganController@changePassword')->name('pelanggan.change_password');
        Route::put('profile/ganti_password/{id}', 'PelangganController@updatePassword')->name('pelanggan.update_password');
        
        Route::put('riwayat_pesanan/detail/{id}/terima', 'PelangganController@terimaBarang')->name('pelanggan.terima_barang');

        Route::get('barang-disukai', 'LikeController@index')->name('pelanggan.liked-items');

        Route::get('checkout', function() {
            return view('client.checkout.form', ['user' => Auth::guard('pelanggan')->user()]);
        })->name('client.checkout');
        
        Route::get('riwayat_pesanan', 'PelangganController@riwayatPesanan')->name('pelanggan.riwayat_pesanan');
        Route::get('riwayat_pesanan/detail/{id}', 'PelangganController@detailPesanan')->name('pelanggan.detail_pesanan');
        Route::get('riwayat_pesanan/detail', function(){
            return redirect()->back();
        });

        Route::put('riwayat_pesanan/cancel/{id}', 'ClientController@cancelOrder')->name('pelanggan.cancel_order');

        //komentar
        Route::post('barang/{slug}/comment', 'KomenController@create')->name('pelanggan.komen');
        
        Route::post('place-order', 'ClientController@placeOrder')->name('pelanggan.order');

        Route::get('thankyou/{id}', 'ClientController@thankyou')->name('pelanggan.order.thankyou');
    });
});

Route::prefix('doku')->group(function() {
    Route::post('identify', 'DokuController@identify');
    Route::post('notify', 'DokuController@notify');
    Route::post('redirect', 'DokuController@redirect');
});

Route::group(['prefix'  => 'api/cart', 'namespace' => 'Api'], function() {
    Route::get('all', 'CartController@cartList')->name('api.cart.all');
    Route::post('add', 'CartController@addToCart')->name('api.cart.add');
    Route::post('update', 'CartController@updateCart')->name('api.cart.update');
    Route::post('delete/{barang}', 'CartController@deleteCart')->name('api.cart.delete');

});

Route::group(['prefix' => 'api/', 'namespace' => 'Api'], function() {
    Route::middleware('auth.client:pelanggan')->group(function() {
        Route::get('likes', 'LikeController@index')->name('api.like.index');
        Route::post('likes/{item_id}', 'LikeController@create')->name('api.like.add');
        Route::post('likes/{item_id}/remove', 'LikeController@remove')->name('api.like.remove');
    });
    Route::get('cost', 'ShippingController@shippingCost')->name('api.shipping.cost');
});

Route::get('/test', function(){
	return view('default');
});


Route::get('admin/', function(){
    return redirect()->route('admin.home');
});

Route::prefix('admin')->group(function() {

    Route::middleware('auth')->group(function() {
        Route::resource('kategori', 'KategoriController');
        Route::get('dashboard', 'HomeController@index')->name('admin.home');
        Route::resource('barang', 'BarangController');
        Route::resource('user', 'UserController');
        Route::get('trash-barang', 'BarangController@showTrash')->name('barang.trash');
        Route::get('barang/{id}/restore', 'BarangController@restore')->name('barang.restore');
        Route::get('pelanggan', 'PelangganController@index')->name('pelanggan.index');
        Route::delete('pelanggan/{id}', 'PelangganController@destroy')->name('pelanggan.destroy');
        Route::resource('pemesanan', 'PemesananController');
        Route::resource('pembayaran', 'PaymentController');


        Route::get('laporan-penjualan', 'LaporanController@laporanPenjualan')->name('laporan.penjualan');

        Route::get('laporan-penjualan/print', 'LaporanController@cetakPenjualan')->name('print.penjualan');

        Route::get('laporan-stock', 'LaporanController@laporanStock')->name('laporan.stock');

        Route::get('laporan-stock/print', 'LaporanController@cetakStock')->name('print.stock');
    });
    
    Auth::routes();
});

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\File;
use App\Model\Barang;
use App\Model\KategoriBarang;
use App\Http\Requests\StoreBarang;
use App\Http\Requests\StoreUpdateBarang;
use Illuminate\Support\Facades\DB;

class BarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(isset($_GET['q'])){
            $data['barang'] = Barang::where('nama_barang', 'like', '%'.$_GET['q'].'%')->get();
        } else {
            $data['barang'] = Barang::paginate(8);
        }
        return view('admin.barang.index', $data);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['kategori'] = KategoriBarang::all();
        return view('admin.barang.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBarang $request)
    {
        $validate = $request->validated();

        if($validate){
            $file_name = doRenameImage($request->file('foto')->getClientOriginalName());
            $store_image = $request->file('foto')->storeAs('gambar_produk', $file_name);
            if($store_image){
                //resize gambar
                try{
                    resizeImage($file_name);
                } catch (Exception $e) {
                    dd($e->getMessage());
                }
            } else {
                notifMsg('danger', 'Gambar gagal diupload, gagal menambah data barang!');
                return redirect()->route('barang.index');
            }
            
            //input ke db
            $barang = Barang::create($request->all());

            
            $barang->foto = $file_name;
            $barang->save();
            //input ke table stok
            
            notifMsg('success', 'Berhasil menambah data barang!');
            return redirect()->route('barang.index');
        } else {
            notifMsg('danger', 'Gagal menambah data barang!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['barang'] = Barang::find($id);
        return view('admin.barang.detail', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['barang'] = Barang::find($id);
        $data['kategori'] = KategoriBarang::all();
        return view('admin.barang.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUpdateBarang $request, $id)
    {
        $validate = $request->validated();
        $barang = Barang::find($id);

        if($validate) {
            //update with gambar

            if($request->foto != null){
                $file_name = $barang->foto;

                $store_image = $request->foto->storeAs('gambar_produk', $file_name);
                
                if($store_image){
                    //resize gambar
                    try{
                        resizeImage($file_name);
                    } catch (Exception $e) {
                        dd($e->getMessage());
                    }
                } else {
                    notifMsg('danger', 'Gambar gagal diupload, gagal mengedit data barang!');
                    return redirect()->route('barang.index');
                }

                 $barang->update([
                     'kategori_id' => $request->kategori_id,
                     'sku' => $request->sku,
                     'slug' => $request->slug,
                     'nama_barang' => $request->nama_barang,
                     'harga' => $request->harga,
                     'foto' => $file_name,
                     'berat' => $request->berat,
                     'lebar' => $request->lebar,
                     'panjang' => $request->panjang,
                     'tinggi' => $request->tinggi,
                     'deskripsi' => $request->deskripsi,
                     'diskon' => $request->diskon,
                     'stock' => $request->stock
                     ]
                 );
                
            } else {
                //without image
                $barang->update($request->toArray());
            }

            if ($request->get('diskon_id') != 0) {
                $barang->setSalePriceBasedDiscount($barang->discount);
            }

            notifMsg('success', 'Berhasil mengedit data barang!');
            return redirect()->route('barang.index');
        } else {
            notifMsg('danger', 'Gagal mengedit data barang!');
            return redirect()->route('barang.index');
        }
        //dd($request->toArray());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = Barang::destroy($id);
        if($delete){
            notifMsg('warning', 'Berhasil menghapus data barang');
            return redirect()->route('barang.index');
        } else {
            notifMsg('danger', 'Gagal menghapus data barang');
            return redirect()->route('barang.index');
        }
    }


    //Trash Barang
    public function showTrash(){
       
        $data['barang'] = Barang::onlyTrashed()->get();
        return view('admin.barang.trash', $data);
    }

    public function restore($id) {
        Barang::onlyTrashed()->where('id_barang', $id)->restore();
        notifMsg('success', 'Berhasil me-restore barang');
        return redirect()->back();
    }
}

resources/views/admin/barang/create.blade.php
@extends('admin.app')

@section('title')
Tambah Barang
@endsection

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h4>Form Barang</h4>
                <hr>
                <form action="{{ route('barang.store') }}" method="post" enctype="multipart/form-data">
                @csrf
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label for="nama_barang">Nama Barang</label>
                            <input type="text" id="nama_barang" class="form-control" placeholder="Masukan Nama Barang" name="nama_barang" value="{{ old('nama_barang') }}" onkeyup="makeSlug()">
                        </div>
                        <div class="col-sm-6">
                            <label for="kategori_id">Kategori</label>
                            <select name="kategori_id" class="form-control" required>
                                <option value=""> - Pilih Kategori - </option>
                                @foreach($kategori as $option)
                                <option value="{{ $option->id_kategori }}">{{ $option->nama_kategori }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label for="sku">SKU</label>
                            <input type="text" class="form-control" placeholder="Masukan SKU" name="sku" value="{{ old('sku') }}">
                        </div>
                        <div class="col-sm-6">
                        <label for="harga">Harga</label>
                            <input type="number" class="form-control" placeholder="Masukan Harga" name="harga" value="{{ old('harga') }}">
                        </div>
                        <input type="hidden" id="slug" class="form-control" placeholder="Masukan Slug" name="slug" value="{{ old('slug') }}">
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label for="sku">Stock</label>
                            <input type="number" class="form-control" placeholder="Masukan Stock" name="stock" value="{{ old('stock') }}">
                        </div>
                        <div class="col-sm-6">
                        <label for="harga">Diskon</label>
                            <div class="input-group">
                                <input type="number" class="form-control" placeholder="Masukan Diskon" name="diskon" value="{{ old('diskon') }}">
                                <div class="input-group-append">
                                    <span class="input-group-text">%</span>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                    <div class="form-group row">
                        <div class="col-md-3">
                            <label for="">Berat</label>
                            <div class="input-group">
                                <input type="number" name="berat" id="" class="form-control" value="{{ old('berat') }}">
                                <div class="input-group-append">
                                    <span class="input-group-text">gram</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <label for="">Panjang</label>
                            <div class="input-group">
                                <input type="number" name="panjang" id="" class="form-control" value="{{ old('panjang') }}">
                                <div class="input-group-append">
                                    <span class="input-group-text">CM</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <label for="">Lebar</label>
                            <div class="input-group">
                                <input type="number" name="lebar" id="" class="form-control" value="{{ old('lebar') }}">
                                <div class="input-group-append">
                                    <span class="input-group-text">CM</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <label for="">Tinggi</label>
                            <div class="input-group">
                                <input type="number" name="tinggi" id="" class="form-control" value="{{ old('tinggi') }}">
                                <div class="input-group-append">
                                    <span class="input-group-text">CM</span>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="gambar">Gambar</label>
                            <input type="file" class="form-control" placeholder="Masukan Gambar" name="foto" value="{{ old('gambar') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="deskripsi">Deskripsi</label>
                            <textarea id="editor1" name="deskripsi" class="form-control" id="editor" rows="4" placeholder="Masukan deksripsi yang menarik disini"></textarea>
                        </div>
                    </div>
                    <div class="form-group row mr-auto">
                        <div class="col-sm-12">
                            <input type="submit" class="btn btn-success" value="Simpan">                    
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div> 
@endsection

@push('scripts')

<script>

function makeSlug(){
    var barangName = $('#nama_barang').val();
    var slugName = barangName.split(' ').join('-').toLowerCase();
    $('#slug').val(slugName);
}
</script>

<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>

<script>
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace( 'editor1' );
</script>


@endpush

resources/views/admin/barang/detail.blade.php
@extends('admin.app')

@section('title')
Detail Barang {{ $barang->nama_barang }}
@endsection

@section('content')
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">{{ $barang->nama_barang }}</h4>
                <hr>
                <img src="<?= asset('storage/gambar_produk').'/'.$barang->foto ?>" alt="{{ $barang->foto }}" class="img-fluid">
                <table class="table">
                    <tr>
                        <td>SKU</td>
                        <td>:</td>
                        <td>{{ $barang->sku }}</td>
                    </tr>
                    <tr>
                        <td>Harga</td>
                        <td>:</td>
                        <td>{{ $barang->checkDiscount() }}</td>
                    </tr>
                    <tr>
                        <td>SLUG</td>
                        <td>:</td>
                        <td>{{ $barang->slug }}</td>
                    </tr>
                    <tr>
                        <td>Stock</td>
                        <td>:</td>
                        <td>{{ $barang->stock }}</td>
                    </tr>
                    <tr>
                        <td>Berat</td>
                        <td>:</td>
                        <td>{{ $barang->berat }} gram</td>
                    </tr>
                    <tr>
                        <td>Panjang</td>
                        <td>:</td>
                        <td>{{ $barang->panjang }} CM</td>
                    </tr>
                    <tr>
                        <td>Lebar</td>
                        <td>:</td>
                        <td>{{ $barang->lebar }} CM</td>
                    </tr>
                    <tr>
                        <td>Tinggi</td>
                        <td>:</td>
                        <td>{{ $barang->tinggi }} CM</td>
                    </tr>
                </table>
                <p><strong>Deskripsi Barang:</strong></p>
                    <?= $barang->deskripsi ?>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/barang/edit.blade.php
@extends('admin.app')

@section('title')
Edit Data Barang
@endsection

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h4>Form Edit Barang</h4>
                <hr>
                <form action="{{ route('barang.update', ['id' => $barang->id_barang]) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('put')
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label for="nama_barang">Nama Barang</label>
                            <input type="text" id="nama_barang" class="form-control" placeholder="Masukan Nama Barang" name="nama_barang" value="{{ $barang->nama_barang }}" onkeyup="makeSlug()">
                        </div>
                        <div class="col-sm-6">
                            <label for="kategori_id">Kategori</label>
                            <select name="kategori_id" class="form-control" required>
                                <option value=""> - Pilih Kategori - </option>
                                @foreach($kategori as $option)
                                <option value="{{ $option->id_kategori }}" {{ $option->id_kategori == $barang->kategori_id ? "selected" : "" }}>{{ $option->nama_kategori }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label for="sku">SKU</label>
                            <input type="text" class="form-control" placeholder="Masukan SKU" name="sku" value="{{ $barang->sku }}">    
                        </div>
                        <div class="col-sm-6">
                            <label for="harga">Harga</label>
                            <input type="text" class="form-control" placeholder="Masukan Harga" name="harga" value="{{ $barang->harga }}">
                        </div>
                        <input type="hidden" id="slug" class="form-control" placeholder="Masukan Slug" name="slug" value="{{ $barang->slug }}">
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-6">
                            <label for="sku">Stock</label>
                            <input type="number" class="form-control" placeholder="Masukan Stock" name="stock" value="{{ $barang->stock }}">
                        </div>
                        <div class="col-sm-6">
                        <label for="harga">Diskon</label>
                            <div class="input-group">
                                <input type="number" class="form-control" placeholder="Masukan Diskon" name="diskon" value="{{ $barang->diskon }}">
                                <div class="input-group-append">
                                    <span class="input-group-text">%</span>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                    <div class="form-group row">
                        <div class="col-md-3">
                            <label for="">Berat</label>
                            <div class="input-group">
                                <input type="number" name="berat" id="" class="form-control" value="{{ $barang->berat }}">
                                <div class="input-group-append">
                                    <span class="input-group-text">gram</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <label for="">Panjang</label>
                            <div class="input-group">
                                <input type="number" name="panjang" id="" class="form-control" value="{{ $barang->panjang }}">
                                <div class="input-group-append">
                                    <span class="input-group-text">CM</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <label for="">Lebar</label>
                            <div class="input-group">
                                <input type="number" name="lebar" id="" class="form-control" value="{{ $barang->lebar }}">
                                <div class="input-group-append">
                                    <span class="input-group-text">CM</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <label for="">Tinggi</label>
                            <div class="input-group">
                                <input type="number" name="tinggi" id="" class="form-control" value="{{ $barang->tinggi }}">
                                <div class="input-group-append">
                                    <span class="input-group-text">CM</span>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="gambar">Gambar</label>
                            <input type="file" class="form-control" placeholder="Masukan Gambar" name="foto" >
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="deskripsi">Deskripsi</label>
                            <textarea id="editor1" name="deskripsi" class="form-control" rows="4" placeholder="Masukan deksripsi yang menarik disini">{{ $barang->deskripsi }}</textarea>
                        </div>
                    </div>
                    <div class="form-group row mr-auto">
                        <div class="col-sm-12">
                            <input type="submit" class="btn btn-success" value="Simpan">                    
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div> 
@endsection

@push('scripts')

<script>

function makeSlug(){
    var barangName = $('#nama_barang').val();
    var slugName = barangName.split(' ').join('-').toLowerCase();
    $('#slug').val(slugName);
}
</script>


<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>

<script>
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace( 'editor1' );
</script>

@endpush

resources/views/admin/barang/index.blade.php
@extends('admin.app')

@section('title')
Barang
@endsection

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
        
                <a href="{{ route('barang.create') }}" class="btn btn-outline-primary">Tambah Barang</a>
                <br><br>
                <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">SKU</th>
                                <th scope="col">Nama Barang</th>
                                <th scope="col">Kategori</th>
                                <th scope="col">Stock</th>
                                <th scope="col">Harga</th>
                                <th scope="col">Gambar</th>
                                <th scope="col">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($barang as $data)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $data->sku }}</td>
                                    <td>{{ $data->nama_barang}}</td>
                                    <td>{{ $data->category->nama_kategori }}</td>
                                    <td>{{ $data->stock }}</td>
                                    <td>{{ $data->checkDiscount() }}</td>
                                    <td><img src="<?= asset('storage/gambar_produk/small').'/'.$data->foto ?>" alt="{{ $data->foto }}" width="100px"></td>
                                        <!-- form (for delete) -->
                                        <form action="{{ route('barang.destroy', ['id' => $data->id_barang] ) }}" id="delete-barang" method="post">
                                            <!-- EDIT BUTTON -->
                                            <td>
                                                <a href="{{ route('barang.show', ['id' => $data->id_barang]) }}" class="btn btn-sm btn-primary btn-product">Detail</a>
                                                <a href="{{ route('barang.edit', ['id' => $data->id_barang]) }}" class="btn btn-sm btn-warning btn-product">Edit</a>
                                           
                                                <!-- DELETE BUTTON -->
                                                <button type="submit" class="btn btn-danger btn-sm btn-product" onclick="return confirm('Yakin Hapus Data?')">
                                                    Hapus 
                                                </button>
                                            </td>
                                            @csrf 
                                            @method('DELETE')
                                        </form>
                                        <!-- END FORM -->
                                    
                                </tr>
                            @endforeach
                            
                        </tbody>
                </table>
                @if ($barang instanceof \Illuminate\Pagination\LengthAwarePaginator )
                    {{ $barang->links() }}
                @endif
            </div>
        </div>
    </div>
</div> 
@endsection