routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Clients\ClientController@index')->name('client.home');

Route::get('barang/', 'Clients\ClientController@showBarang')->name('client.show_barang');

Route::get('barang/{slug}', 'Clients\ClientController@detailBarang')->name('client.detail_barang');

Route::get('barang/kategori/{id}', 'Clients\ClientController@showKategori')->name('client.kategori');

Route::get('barang/search','Clients\ClientController@searchBarang')->name('barang.search');

Route::get('about', function(){
    return view('client.about');
});

Route::namespace('Clients')->group(function() {
    Route::get('register/', 'PelangganLoginController@showRegisterForm')->name('pelanggan.registerForm');
    Route::post('register', 'PelangganLoginController@register')->name('pelanggan.register');
    Route::get('login', 'PelangganLoginController@showLoginForm')->name('pelanggan.loginForm');
    Route::post('login', 'PelangganLoginController@login')->name('pelanggan.login');
    Route::post('logout', 'PelangganLoginController@logout')->name('pelanggan.logout');
    //auth

    Route::middleware('auth.client:pelanggan')->group(function(){
        Route::get('profile/{id}', 'PelangganController@index')->name('pelanggan.profile');
        Route::get('profile/edit/{id}', 'PelangganController@edit')->name('pelanggan.edit-profile');
        Route::put('profile/edit/{id}', 'PelangganController@update')->name('pelanggan.update');
        Route::get('profile/ganti_password/{id}', 'PelangganController@changePassword')->name('pelanggan.change_password');
        Route::put('profile/ganti_password/{id}', 'PelangganController@updatePassword')->name('pelanggan.update_password');
        
        Route::put('riwayat_pesanan/detail/{id}/terima', 'PelangganController@terimaBarang')->name('pelanggan.terima_barang');

        Route::get('barang-disukai', 'LikeController@index')->name('pelanggan.liked-items');

        Route::get('checkout', function() {
            return view('client.checkout.form', ['user' => Auth::guard('pelanggan')->user()]);
        })->name('client.checkout');
        
        Route::get('riwayat_pesanan', 'PelangganController@riwayatPesanan')->name('pelanggan.riwayat_pesanan');
        Route::get('riwayat_pesanan/detail/{id}', 'PelangganController@detailPesanan')->name('pelanggan.detail_pesanan');
        Route::get('riwayat_pesanan/detail', function(){
            return redirect()->back();
        });

        Route::put('riwayat_pesanan/cancel/{id}', 'ClientController@cancelOrder')->name('pelanggan.cancel_order');

        //komentar
        Route::post('barang/{slug}/comment', 'KomenController@create')->name('pelanggan.komen');
        
        Route::post('place-order', 'ClientController@placeOrder')->name('pelanggan.order');

        Route::get('thankyou/{id}', 'ClientController@thankyou')->name('pelanggan.order.thankyou');
    });
});

Route::prefix('doku')->group(function() {
    Route::post('identify', 'DokuController@identify');
    Route::post('notify', 'DokuController@notify');
    Route::post('redirect', 'DokuController@redirect');
});

Route::group(['prefix'  => 'api/cart', 'namespace' => 'Api'], function() {
    Route::get('all', 'CartController@cartList')->name('api.cart.all');
    Route::post('add', 'CartController@addToCart')->name('api.cart.add');
    Route::post('update', 'CartController@updateCart')->name('api.cart.update');
    Route::post('delete/{barang}', 'CartController@deleteCart')->name('api.cart.delete');

});

Route::group(['prefix' => 'api/', 'namespace' => 'Api'], function() {
    Route::middleware('auth.client:pelanggan')->group(function() {
        Route::get('likes', 'LikeController@index')->name('api.like.index');
        Route::post('likes/{item_id}', 'LikeController@create')->name('api.like.add');
        Route::post('likes/{item_id}/remove', 'LikeController@remove')->name('api.like.remove');
    });
    Route::get('cost', 'ShippingController@shippingCost')->name('api.shipping.cost');
});

Route::get('/test', function(){
	return view('default');
});


Route::get('admin/', function(){
    return redirect()->route('admin.home');
});

Route::prefix('admin')->group(function() {

    Route::middleware('auth')->group(function() {
        Route::resource('kategori', 'KategoriController');
        Route::get('dashboard', 'HomeController@index')->name('admin.home');
        Route::resource('barang', 'BarangController');
        Route::resource('user', 'UserController');
        Route::get('trash-barang', 'BarangController@showTrash')->name('barang.trash');
        Route::get('barang/{id}/restore', 'BarangController@restore')->name('barang.restore');
        Route::get('pelanggan', 'PelangganController@index')->name('pelanggan.index');
        Route::delete('pelanggan/{id}', 'PelangganController@destroy')->name('pelanggan.destroy');
        Route::resource('pemesanan', 'PemesananController');
        Route::resource('pembayaran', 'PaymentController');


        Route::get('laporan-penjualan', 'LaporanController@laporanPenjualan')->name('laporan.penjualan');

        Route::get('laporan-penjualan/print', 'LaporanController@cetakPenjualan')->name('print.penjualan');

        Route::get('laporan-stock', 'LaporanController@laporanStock')->name('laporan.stock');

        Route::get('laporan-stock/print', 'LaporanController@cetakStock')->name('print.stock');
    });
    
    Auth::routes();
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Model\Barang;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'no_telp', 'level'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $primaryKey = 'id_user';

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($val) {
        return $this->attributes['password'] = bcrypt($val);
    }

    public function updatePassword(string $new) {
        $this->password = $new;
        $this->save();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $s = $request->has('q') ? $request->get('q') : '';
        $users = new User;

        if (!empty($s)) {
            $users = $users->where('name', $s)->orWhere('email', $s);
        }

        return view('admin.user.index', ['users' => $users->paginate(10)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request)
    {
        $user = User::create($request->all());
        if (!$user) {
            
            return redirect()->route('user.index')->with('error', 'Gagal menambah data user!');
            
        }
        return redirect()->route('user.index')->with('success', 'Berhasil menambah data user!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('admin.user.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        $user = User::findOrFail($id)->update($request->all());

        if ($request->has('password')) {
            $user->updatePassword($request->get('password'));
        }

        if (!$user) {
            return redirect()->route('user.index')->with('success', 'Gagal mengupdate data user!');
        
        }
        return redirect()->route('user.index')->with('success', 'Berhasil mengupdate data user!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::destroy($id);
        if (!$user) {
            return redirect()->route('user.index')->with('error', 'Gagal menghapus data user!');
        }

        return redirect()->route('user.index')->with('error', 'Berhasil menghapus data user!');
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.app')

@section('title')
Tambah User
@endsection

@section('content')

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h4>Form User</h4>
                <hr>
                <form action="{{ route('user.store') }}" method="post">
                @csrf
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="">Nama User</label>
                            <input type="text" class="form-control" id="name" placeholder="Nama" name="name" value="{{ old('name') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="">Email</label>
                            <input type="text" class="form-control" id="email" placeholder="Email" name="email" value="{{ old('email') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="">No Telp</label>
                            <input type="text" class="form-control" id="no_telp" placeholder="No Telp" name="no_telp" value="{{ old('no_telp') }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="">Password</label>
                            <input type="password" class="form-control" id="password" placeholder="Password" name="password" value="">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="">Konfirmasi Password</label>
                            <input type="password" class="form-control" id="password_confirmation" placeholder="Password Konfirmasi" name="password_confirmation" value="">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="">Level</label>
                            <select name="level" class="form-control">
                                <option value=""> - Pilih Level - </option>
                                <option value="0">Admin</option>
                                <option value="1">Owner</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mr-auto">
                        <div class="col-sm-12">
                            <input type="submit" class="btn btn-success" value="Simpan">                    
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div> 
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.app')

@section('title')
Edit User
@endsection

@section('content')

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h4>Form User</h4>
                <hr>
                <form action="{{ route('user.update', $user->id_user) }}" method="post">
                @method('PUT')
                @csrf
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="">Nama User</label>
                            <input type="text" class="form-control" id="name" placeholder="Nama" name="name" value="{{ $user->name }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="">Email</label>
                            <input type="text" class="form-control" id="email" placeholder="Email" name="email" value="{{ $user->email }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="">No Telp</label>
                            <input type="text" class="form-control" id="no_telp" placeholder="No Telp" name="no_telp" value="{{ $user->no_telp }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-12">
                            <label for="">Level</label>
                            <select name="level" class="form-control">
                                <option value=""> - Pilih Level - </option>
                                <option value="0" {{ ($user->level == 0 ) ? 'selected' : '' }} >Admin</option>
                                <option value="1" {{ ($user->level == 1 ) ? 'selected' : '' }} >Owner</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row mr-auto">
                        <div class="col-sm-12">
                            <input type="submit" class="btn btn-success" value="Simpan">                    
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div> 
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.app')

@section('title')
User
@endsection

@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
        
                <a href="{{ route('user.create') }}" class="btn btn-outline-primary">Tambah User</a>
                <br><br>
                <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nama</th>
                                <th scope="col">Email</th>
                                <th>Level</th>
                                <th scope="col">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ ($user->level == 1) ? 'Owner' : 'Admin' }}</td>
                                    
                                        <!-- form (for delete) -->
                                        <form action="{{ route('user.destroy', ['id' => $user->id_user] ) }}" id="delete-user" method="post">
                                            <!-- EDIT BUTTON -->
                                            <td>
                                                <a href="{{ route('user.edit', ['id' => $user->id_user]) }}" class="btn btn-sm btn-warning">Edit</a>
                                           
                                            <!-- DELET BUTTON -->
                                           
                                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Yakin Hapus user?')">
                                                    Hapus 
                                                </button>
                                            </td>
                                            @csrf 
                                            @method('DELETE')
                                        </form>
                                        <!-- END FORM -->
                                    
                                </tr>
                            @endforeach
                            
                        </tbody>
                </table>
                {!! $users->links() !!}
            </div>
        </div>
    </div>
</div> 
@endsection